version: "3.8"
services:
  api:
    build: .
    container_name: delay_api
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - backend

  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transport
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
